package com.main.CoreWorks.Generators;

import com.main.CoreWorks.RunPersistence.*;

import java.util.Random;

/*
Summary of how nodes are built:

CombatNode --> Stores the enemies generated by combatGenerator in the node itself, which will then be accessed by CombatScreen to generate the fight
 */
public class RunMapGenerator {
    public static RunMap generateRunMap(RunState runState) {
        // Right now, the runMap is hardcoded for testing, but we plan to eventually get it randomly generated

        RunMap runMap = new RunMap();
        Random random = runState.getRandom();

        // Generate all the nodes of the current floor + map position (via x and y coords)
        CombatNode combat1 = new CombatNode(CombatGenerator.createCombat(1, 0.9f, random), 1, 0.9f, 150, 500);
        CombatNode combat2 = new CombatNode(CombatGenerator.createCombat(1, 1f, random), 1, 1f, 450, 500);
        CombatNode combat3 = new CombatNode(CombatGenerator.createCombat(1, 1.1f, random), 1, 1.1f, 750, 500);
        CombatNode combat4 = new CombatNode(CombatGenerator.createCombat(1, 1.5f, random), 1, 1.5f, 1050, 500);
        RestNode rest1 = new RestNode(1, 1.1f,750, 250);
        BossNode boss1 = new BossNode(CombatGenerator.createCombat("Boss1", 1.8f, random), 1, 1.8f, 1500, 500);

        // Determine how the nodes link to other nodes
        combat1.addNextNode(combat2);
        combat2.addNextNode(combat3);
        combat2.addNextNode(rest1);
        rest1.addNextNode(combat4);
        combat3.addNextNode(combat4);
        combat4.addNextNode(boss1);

        // Adds the nodes to the map
        runMap.addNode(combat1);
        runMap.addNode(combat2);
        runMap.addNode(combat3);
        runMap.addNode(combat4);
        runMap.addNode(rest1);
        runMap.addNode(boss1);

        // Set the starting node
        runMap.setStartNode(combat1);

        // Unlock the start node for clicking
        combat1.setUnlocked(true);

        return runMap;
    }
}
