package com.main.CoreWorks.Generators;

import com.badlogic.gdx.utils.Array;
import com.main.CoreWorks.RunPersistence.*;

import java.util.Comparator;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;

/*
Summary of how nodes are built:

CombatNode --> Stores the enemies generated by combatGenerator in the node itself, which will then be accessed by CombatScreen to generate the fight
 */
public class RunMapGenerator {
    // Simple code for testing any changes to map
    public static RunMap generateHardcodedRunMap(RunState runState) {
        // Right now, the runMap is hardcoded for testing, but we plan to eventually get it randomly generated

        RunMap runMap = new RunMap();
        Random random = runState.getRandom();

        // Generate all the nodes of the current floor + map position (via x and y coords)
        CombatNode combat1 = new CombatNode(CombatGenerator.createCombat(1, 0.9f, random), 1, 0.9f, 150, 500);
        CombatNode combat2 = new CombatNode(CombatGenerator.createCombat(1, 1f, random), 1, 1f, 450, 500);
        CombatNode combat3 = new CombatNode(CombatGenerator.createCombat(1, 1.1f, random), 1, 1.1f, 750, 500);
        CombatNode combat4 = new CombatNode(CombatGenerator.createCombat(1, 1.5f, random), 1, 1.5f, 1050, 500);
        RestNode rest1 = new RestNode(1, 1.1f,750, 250);
        BossNode boss1 = new BossNode(CombatGenerator.createCombat("Boss1", 1.8f, random), 1, 1.8f, 1500, 500);

        // Determine how the nodes link to other nodes
        combat1.addNextNode(combat2);
        combat2.addNextNode(combat3);
        combat2.addNextNode(rest1);
        rest1.addNextNode(combat4);
        combat3.addNextNode(combat4);
        combat4.addNextNode(boss1);

        // Adds the nodes to the map
        runMap.addNode(combat1);
        runMap.addNode(combat2);
        runMap.addNode(combat3);
        runMap.addNode(combat4);
        runMap.addNode(rest1);
        runMap.addNode(boss1);

        // Set the starting node
        runMap.setStartNode(combat1);

        // Unlock the start node for clicking
        combat1.setUnlocked(true);

        return runMap;
    }

    // Main RunMap generation code that generates the first floor (can be copy-pasted and edited for generating another floor perhaps?)
    public static RunMap generateRandomRunMapF1(RunState runState) {
        // Determines how many rows and cols the map will have max (will not be using the full number ofc, just to scale the spacing)
        int totalCols = 6;
        int totalRows = 10;

        // Determines the 4 bounds of the map
        float leftBound = -100f;
        float rightBound = 1500f;
        float topBound = 575f;
        float bottomBound = -800f;

        RunMap runMap = new RunMap();
        Random random = runState.getRandom();

        // Nested array of arrays of nodes, each internal array represents rows, external array represents the full map
        Array<Array<MapNode>> allNodes = new Array<>();

        // Creates the start Node (Guaranteed to be a combat node)
        Array<MapNode> startRowNode = new Array<>();
        int startCol = totalCols / 2;
        float startX = generateXCoords(startCol, totalCols, leftBound, rightBound);
        float startY = generateYCoords(0, totalRows, topBound, bottomBound);
        MapNode startNode = new CombatNode(CombatGenerator.createCombat(1,0.9f, random), 0, startCol, 1, 0.9f, startX, startY);
        startRowNode.add(startNode);
        allNodes.add(startRowNode);

        // Creates all random nodes in between, except the boss node
        for (int i = 1; i < totalRows - 1; i++) {
            Array<MapNode> middleRowNodes = new Array<>();

            // lognormal distribution (dont worry abt it)
            double m = 1.2;
            double var = Math.pow(1 / m, 2) / 2;
            double s2 = Math.log(1 + var / (m*m));
            double mu  = Math.log(m) - s2/2;
            double nodes = Math.expm1(random.nextGaussian(mu, Math.sqrt(s2))) + 1;

            int numNodes = (int) Math.min(3 + nodes, totalCols); // Guarantees a certain number of nodes, but never more than the number of cols available

            // This will pick random unique columns to draw the node
            Array<Integer> uniqueCols = new Array<>();
            while (uniqueCols.size < numNodes) {
                int uniqueCol = random.nextInt(totalCols);
                if (!uniqueCols.contains(uniqueCol, false)) {
                    uniqueCols.add(uniqueCol);
                }
            }

            // This will create the actual node itself
            for (int j = 0; j < uniqueCols.size; j++) {
                int randomCol = uniqueCols.get(j);
                float randomX = generateXCoords(randomCol, totalCols, leftBound, rightBound);
                float randomY = generateYCoords(i, totalRows, topBound, bottomBound);
                MapNode randomNode = createRandomNodeF1(i, totalRows, randomCol, randomX, randomY, random);
                middleRowNodes.add(randomNode);
            }
            allNodes.add(middleRowNodes);
        }

        // Creates the boss node
        Array<MapNode> bossRowNode = new Array<>();
        int bossCol = totalCols / 2;
        float bossX = generateXCoords(bossCol, totalCols, leftBound, rightBound);
        float bossY = generateYCoords(totalRows - 1, totalRows, topBound, bottomBound);
        bossRowNode.add(new BossNode(CombatGenerator.createCombat("Boss1",2f, random), totalRows - 1, bossCol, 1, 2f, bossX, bossY));
        allNodes.add(bossRowNode);

        // Connect the rows
        for (int row = 0; row < allNodes.size - 1; row++) {
            connectRows(allNodes.get(row), allNodes.get(row + 1), random);
        }

        // Add all the nodes to a RunMap
        for (Array<MapNode> rowNodes : allNodes) {
            for (MapNode node : rowNodes) {
                runMap.addNode(node);
            }
        }

        // Set the start Node as unlocked + starting Node
        startNode.setUnlocked(true);
        runMap.setStartNode(startNode);

        return runMap;

    }

    // Helper function to connect the different rows
    private static void connectRows(Array<MapNode> fromRow, Array<MapNode> toRow, Random random) {
        // Sort nodes by column number to make the map less criss-crossy
        fromRow.sort(Comparator.comparingInt(MapNode::getCol));
        toRow.sort(Comparator.comparingInt(MapNode::getCol));

        // Connect nodes that are close without criss-crossing as much as possible
        for (MapNode fromNode : fromRow) {
            for (MapNode toNode : toRow) {
                // Look only for nodes within x columns away
                if (Math.abs(fromNode.getCol() - toNode.getCol()) <= 1) {
                    // If it crosses, do not add a connection
                    if (willCross(fromNode, toNode, fromRow)) {
                        continue;
                    }

                    // otherwise, add the connection, minimally 1, with a chance of more
                    if (random.nextBoolean() || fromNode.getNextNodes().isEmpty()) {
                        fromNode.addNextNode(toNode);
                    }
                }
            }
        }

        // Ensure every node has at least 1 outgoing edge, else force it on the closest node
        for (MapNode fromNode : fromRow) {
            if (fromNode.getNextNodes().isEmpty()) {
                MapNode closestNode = null;
                int closestNodeColDiff = Integer.MAX_VALUE;
                for (MapNode toNode : toRow) {
                    int colDiff = Math.abs(fromNode.getCol() - toNode.getCol());
                    if (colDiff < closestNodeColDiff && !willCross(fromNode, toNode, fromRow)) {
                        closestNodeColDiff = colDiff;
                        closestNode = toNode;
                    }
                }
                if (closestNode != null) {
                    fromNode.addNextNode(closestNode);
                }
            }
        }

        // Ensure every node has at least 1 incoming edge, if not, force it on the closest node
        for (MapNode toNode : toRow) {
            boolean hasIncomingEdge = false;
            for (MapNode fromNode : fromRow) {
                if (fromNode.getNextNodes().contains(toNode, true)) {
                    hasIncomingEdge = true;
                    break;
                }
            }

            if (!hasIncomingEdge) {
                MapNode closestNode = null;
                int closestNodeColDiff = Integer.MAX_VALUE;
                for (MapNode fromNode : fromRow) {
                    int colDiff = Math.abs(fromNode.getCol() - toNode.getCol());
                    if (colDiff < closestNodeColDiff && !willCross(fromNode, toNode, fromRow)) {
                        closestNodeColDiff = colDiff;
                        closestNode = fromNode;
                    }
                }
                if (closestNode != null) {
                    closestNode.addNextNode(toNode);
                }
            }
        }
    }

    // Helper function to check if any connection would cross
    // Friendly note: LibGDX array uses more restrictive iterator instances, so functions that would be nested inside an outer libGDX array iterator loop  ('for ( X x : Y )' loops) like this helper method would break if this function ALSO used the iterator (e.g passed as a parameter in this case)
    // Thus, have to use index based for-loops to bypass this optimization restriction in the nested function code and avoid using the iterator directly
    private static boolean willCross(MapNode fromNode, MapNode toNode, Array<MapNode> fromRow) {
        for (int i = 0; i < fromRow.size; i++) {
            MapNode otherFromNode = fromRow.get(i);
            for (int j = 0; j < otherFromNode.getNextNodes().size; j++) {
                MapNode otherToNode = otherFromNode.getNextNodes().get(j);
                // Cross condition 1: fromNode is left of otherFromNode, but tries to connect the toNode that is on the right of otherToNode
                if (fromNode.getCol() < otherFromNode.getCol() && toNode.getCol() > otherToNode.getCol()) {
                    return true;
                }

                // Cross condition 2: fromNode is right of otherFromNode, but tries to connect the toNode that is on the left of otherToNode
                if (fromNode.getCol() > otherFromNode.getCol() && toNode.getCol() < otherToNode.getCol()) {
                    return true;
                }
            }
        }

        return false;
    }

    // Helper function to generate x coordinates based on node's current column relative to total number of allowed columns
    private static float generateXCoords(int col, int totalCols, float leftBound, float rightBound) {
        float spacing = (rightBound - leftBound) / (totalCols - 1);
        return leftBound + col * spacing;
    }

    // Helper function to generate y coordinates based on node's current row relative to total number of allowed rows
    private static float generateYCoords(int row, int totalRows, float topBound, float bottomBound) {
        float spacing = (topBound - bottomBound) / (totalRows - 1);
        return topBound - row * spacing;
    }

    // Helper function that generates a random node for floor 1, scaling based on the row
    // Eventually when we add more nodes and node screens, there will be more variety
    private static MapNode createRandomNodeF1(int row, int totalRows, int col, float x, float y, Random random) {
        float difficulty = 0.8f + row * 0.1f;
        int val = random.nextInt(100);

        // If it is the 2nd last row (ie before boss), give a higher chance for rest node
        if (row == totalRows - 2) {
            if (val < 50) {
                return new RestNode(1, row, col, difficulty, x, y);
            } else if (val < 90) {
                return new CombatNode(CombatGenerator.createCombat(1, difficulty, random), row, col, 1, difficulty, x, y);
            } else {
                return new EliteNode(CombatGenerator.createCombat("Elite1", difficulty, random), row, col, 1, difficulty, x, y);
            }
        }

        // Else, most likely should be a combat node
        if (val < 15) {
            return new RestNode(1, row, col, difficulty, x, y);
        } else if (val < 75) {
            return new CombatNode(CombatGenerator.createCombat(1, difficulty, random), row, col, 1, difficulty, x, y);
        } else {
            return new EliteNode(CombatGenerator.createCombat("Elite1", difficulty, random), row, col, 1, difficulty, x, y);
        }
    }
}
